### PR TITLE
#349 Create Logo

### LINKED ISSUE #349: Create Logo
Criteria:
1. People need dramatic examples to shake them out of apathy, and I can't do that as Bruce Wayne. As a man, I'm flesh and blood. I can be ignored, I can be destroyed. But as a symbol...as a symbol, I can be incorruptible. I can be everlasting.

### PR DESCRIPTION
**Pull request by ycewe**
Merges #348 
Closes #349 

Features:
1. Website has a favicon
2. Website uses STePS Networking Module title
3. Website implements a logo
4. Navbar on login and signup no longer has links to other pages

### CODE REVIEW

**Comment by Muhammad-Adam** [comment]
capture
This is what I get

**Comment by ycewe** [comment]
@Muhammad-Adam issue resolved. Please review

**Comment by Muhammad-Adam** [comment]
@ycewe Resolve conflict first. I think the conflict came from your other pull request which I just merged. And also, I cant seem to see the favicon.

**Comment by ycewe** [comment]
@Muhammad-Adam You can't see it cause you are not worthy... And you need to clear your browser cache or go incognito

**Comment by Muhammad-Adam** [comment]
capture
Why the icon like that?

**Comment by ycewe** [comment]
I cannot reproduce your issue. How did you get there? Actually I'm surprise you can even run gulp because of a syntax error. Check again. @Muhammad-Adam

**Comment by Muhammad-Adam** [comment]
I added the closing parenthesis myself.

**Comment by ycewe** [comment]
That's not the issue. The issue is I cannot reproduce the error. 
image

Mobile
image

**Pull request merged**
